[build-system]
requires = ["setuptools >= 82.0.1"]
build-backend = "setuptools.build_meta"

[project]
name = "polycog-cognition"
dynamic = ["version"]
dependencies = [
    "pydantic-ai-slim[spec] ~= 2.9.1",
    "networkx ~= 3.6.1",
    "types-networkx ~= 3.6.1.0",
]
requires-python = ">=3.13"
authors = [
    { name="Nate Derbinsky", email="nate@polycog.ai" }
]
description = "Polycog cognition library"
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]
keywords = [
    "ai",
    "neurosymbolic",
]

[project.urls]
Homepage = "https://polycog.ai"
Repository = "https://github.com/polycog/cognition.git"

[tool.setuptools.dynamic]
version = {attr = "cognition.__version__"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"cognition" = ["py.typed"]

[tool.black]
target-version = ["py313",]

[tool.mypy]
python_version = "3.13"
strict = true

[tool.pylint.MAIN]
ignored-classes = ["AttrReferral"]

[tool.pylint.similarities]
min-similarity-lines=8
