name: checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # max-parallel: 1
      matrix:
        python-version: ["3.13", "3.14"]

    steps:
    - name: Check out repository
      uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install mypy pylint ruff black validate-pyproject packaging coverage
    
    - name: Run checks
      run: source checks.sh
